mockery/mockery

- library/Mockery/Container.php
- library/Mockery/Instantiator.php
This is an alternative to #375, I vendored in their instantiator without the caching etc.
> Use customised instantiator

- library/Mockery/Generator/Parameter.php
- library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
- phpunit.xml.dist
- tests/Mockery/MockingVariadicArgumentsTest.php
I'm not that familiar with the internals of Mockey so I may be way off here, but I added a failing test and then attempted an implementation.
Fixes #240 
Let me know if anything needs fixing up
> Support variadic parameters in methods

- library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php
> Added MockeryPHPUnitIntegration.

- tests/Mockery/MockTest.php
Hey there. I just fixt a small typo in the test name.
> Fixed typo

- CHANGELOG.md
Someone asked for a tag in the irc channel, suggestions and improvements for the changelog welcome
> Prep a 0.9.4 release

- library/Mockery/Mock.php
- tests/Mockery/MockTest.php
> Try and throw if method names aren't valid

- composer.json
> Bump hamcrest/hamcrest to 2.0-dev

- library/Mockery/Expectation.php
Response to #539 where intention wasn't clear. Just thought I'd clear up the PHPDoc to guide others not to make the same mistakes as I.
> andThrow Parameter Clarification

- tests/Mockery/LoaderTest.php
They are already loaded via Composer.
> No need to require any files

- library/Mockery/Expectation.php
This pull request introduce only refactoring changes, it doesn't modify or introduce any new functionality. I've made it because some time ago I was doing a code review with a friend over my previous pull request and I realized that there were some changes that there were some changes that could be done on the code to increase its readability, understandability and maintainability.
> Refactor issue 459

- library/Mockery/Generator/Method.php
- library/Mockery/Mock.php
- tests/Mockery/MockingParameterAndReturnTypesTest.php
> Handle return type of self

- tests/Bootstrap.php
This PR contains the changes needed to resolve the issues I spotted in https://github.com/padraic/mockery/pull/553#issuecomment-188190052. It also includes some changes to respect Windows paths.
> Add changes to respect COMPOSER_VENDOR_DIRECTORY env var 

- library/Mockery/Generator/MockConfigurationBuilder.php
- tests/Mockery/Fixtures/SemiReservedWordsAsMethods.php
- tests/Mockery/MockeryCanMockClassesWithSemiReservedWordsTest.php
- tests/Mockery/Test/Generator/MockConfigurationBuilderTest.php
> Remove semi reserved words from default black listed methods

- .gitignore
- .php_cs
> Update php_cs and use cache

- library/Mockery/Generator/MockConfigurationBuilder.php
- library/Mockery/Mock.php
- tests/Mockery/MockTest.php
For issue: https://github.com/padraic/mockery/issues/617
> Fix: __debugInfo for xdebug

- docs/reference/startup_methods.rst
First, when I was reading the docs, it was very obscure to me what an instance mock does. Added a paragraph to the docs for better understanding of this concept.
> Elaborating on instance mocks

- CHANGELOG.md
> Mention phpunit listener in changelog

- docs/reference/expectations.rst
Implemented in:
https://github.com/padraic/mockery/pull/306
> Document `andReturnSelf`

- library/Mockery/Mock.php
- tests/Mockery/MockingVoidMethodsTest.php
> Returns null for auto return value of void methods

- docs/reference/phpunit_integration.rst
... because that's what is in the code.
> Use Adapter\Phpunit not Adapter\PHPUnit

- library/Mockery.php
- library/Mockery/Container.php
- library/Mockery/Generator/StringManipulation/Pass/ClassPass.php
- library/Mockery/Generator/StringManipulation/Pass/InterfacePass.php
- tests/Mockery/ContainerTest.php
> Dont require interfaces to exist

- library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
- tests/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPassTest.php
FYI, I found this bug thanks to [phpstan](https://github.com/phpstan/phpstan).
> fix array_merge usage in MagicMethodTypeHintsPass::apply

- .travis.yml
- library/Mockery/Mock.php
- tests/Mockery/ContainerTest.php
I don't know how relevant HHVM is to the userbase, but it didn't take much to fix these.
> HHVM fixes

- .travis.yml
I'm planning on bringing in a couple of new dependencies and we'll want to cover a full range of their respective releases, so doing this as a precursor.
> Attempt to check lower and upper bounds of deps

- .travis.yml
Travis offers nightly builds of PHP to spot upcoming issues early
> Start testing on php nightly, but ignore any failures

- library/Mockery/MockInterface.php
> Removes @internal docblock tag

- docs/reference/spies.rst
Document better the API for spies, especially about
argument matching.
Fixes #604
> Improve spies documentation

- docs/cookbook/index.rst
- docs/cookbook/map.rst.inc
- docs/cookbook/mockery_on.rst
- docs/cookbook/mocking_hard_dependencies.rst
> Add my blog post as cookbook entry

- library/Mockery/ExpectationInterface.php
- library/Mockery/HigherOrderMessage.php
Fixes https://github.com/mockery/mockery/issues/760
Before
After
> chore: improve docblocks / types for a better experience

- library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php
> Declares property

- library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
- library/Mockery/Mock.php
- phpunit.xml.dist
- tests/Mockery/DemeterChainTest.php
- tests/Mockery/Php72LanguageFeaturesTest.php
See https://wiki.php.net/rfc/object-typehint
> Cater for object type hints in PHP 7.2

- CHANGELOG.md
- library/Mockery/Adapter/Phpunit/TestListener.php
- tests/Mockery/Adapter/Phpunit/TestListenerTest.php
Supercedes #695 and fixes #728
> Drop TestListener support for PHPUnit 5.x

- docs/reference/phpunit_integration.rst
> Clean up phpunit integration section

- CHANGELOG.md
- README.md
Mockery is never going to be perfect and if I wait until I think we're ready for a 1.0 release, it'll never happen. So I'm going to tag 1.0 on Friday. 
Edit: This PR is a WIP, probably going to add bits too it throughout the week.
> 1.0 release

- README.md
This PR changes the build badges to SVG for sharper readability ✨
> README: use SVG badges [ci skip]

- composer.json
- library/Mockery/Matcher/PHPUnitConstraint.php
- tests/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegrationTest.php
- tests/Mockery/ContainerTest.php
> Https for composer.json homepage

- docs/mockery/configuration.rst
- library/Mockery/Configuration.php
> Deprecate allowMockingMethodsUnnecessarily

- tests/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegrationTest.php
- tests/Mockery/ExpectationTest.php
- tests/Mockery/Php72LanguageFeaturesTest.php
The codestyle check was failing, this makes it green again.
> Fix codestyle to be compliant with the standards

- tests/Mockery/ExpectationTest.php
- tests/Mockery/MockingNullableMethodsTest.php
- tests/Mockery/MockingParameterAndReturnTypesTest.php
- tests/Mockery/MockingProtectedMethodsTest.php
I've refactored some tests with [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse), [`assertTrue`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertTrue)  and [`assertNull`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertNull) methods.
> Refactoring tests

- library/Mockery.php
- library/Mockery/Container.php
- tests/Mockery/ContainerTest.php
- tests/Mockery/DemeterChainTest.php
Fixes https://github.com/mockery/mockery/issues/768
PHPunit is not running ATM, investigating further.
> Fixed conflicting mock names

- composer.json
All composer packages I know have a short description
> Shorter composer description

- docs/cookbook/class_constants.rst
- library/Mockery/Configuration.php
- library/Mockery/Container.php
- library/Mockery/Generator/MockConfiguration.php
- library/Mockery/Generator/MockConfigurationBuilder.php
- library/Mockery/Generator/StringManipulation/Pass/ConstantsPass.php
- library/Mockery/Generator/StringManipulationGenerator.php
- tests/Mockery/Fixtures/ClassWithConstants.php
- tests/Mockery/Generator/StringManipulation/Pass/ConstantsPassTest.php
- tests/Mockery/MockingClassConstants.php
``` php
\Mockery::getConfiguration()->setConstantsMap([
'ClassName' => [
'CONSTANT_NAME' => 'CONSTANT_VALUE',
]
]);
```
> Map of constants to mock

- library/Mockery/Expectation.php
Changed Expectation#verify return value typehint from bool to void.
Issue reference: #831
> Typehinted return value on Expectation#verify.

- CHANGELOG.md
- docs/reference/partial_mocks.rst
- library/Mockery/Mock.php
- library/Mockery/MockInterface.php
- tests/Mockery/ContainerTest.php
- tests/Mockery/ExpectationTest.php
- tests/Mockery/Generator/StringManipulation/Pass/CallTypeHintPassTest.php
- tests/Mockery/MockTest.php
- tests/Mockery/MockingProtectedMethodsTest.php
It will be removed in Mockery 2
> Deprecates shouldDeferMissing

- CHANGELOG.md
- library/Mockery/HigherOrderMessage.php
- tests/Mockery/SpyTest.php
> Fixes shouldNotHaveReceived with HigherOrderMessage

- CHANGELOG.md
- library/Mockery/CompositeExpectation.php
- tests/Mockery/ExpectationTest.php
> Adds shouldNotReceive to composite expectation

- CHANGELOG.md
- library/Mockery.php
- tests/Mockery/DemeterChainTest.php
- tests/Mockery/DummyClasses/DemeterChain.php
> Adds support for return type hints in Demeter chain

- CHANGELOG.md
- docs/mockery/configuration.rst
- library/Mockery/Configuration.php
- library/Mockery/Mock.php
> Adds config option to disable reflection cache

- .gitignore
- .travis.yml
- Makefile
When you've got a hammer...
My gnumakeness is a little rusty, but I think I got this right.
> Moves composer script to Makefile

- library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
- library/Mockery/Instantiator.php
Just removing a few unused lines of code.
> Remove unused local variables

- CHANGELOG.md
@robertbasic if you're happy to go, merge this and tag when you're ready, thanks :+1:
> Makes note of release and date

- README.md
- update the readme to reflect that v1 has been
released
Signed-off-by: RJ Garcia <rj@bighead.net>
> Readme V1 Doc Updates

- tests/Mockery/CallableSpyTest.php
I think this method is available across the PHPUnits we support...
> Calls the most common method

- tests/Mockery/Fixtures/MethodWithHHVMReturnType.php
(Tweaking fix from 04f847e31aea6d7fd9a5a97adcaab9d33009d845)
> Fixing type error in HHVM methods test file

- library/helpers.php
That import is not used in the file.
> [1.0] Unnecessary import removed from the `helpers.php`.

- library/Mockery/Mock.php
- tests/Mockery/MockingStaticMethodsCalledObjectStyleTest.php
Allow mocking static methods called object style.
> Allow mocking static methods called object style

- tests/Mockery/MockingNullableMethodsTest.php
Change test name: from Nullabe to Nullable.
> Test name fix

- README.md
Update [Build Status] path to the correct repo and branch.
> Update README.md for 0.9 branch

- Makefile
This is the companion to https://github.com/mockery/mockery/pull/924.
> Added PHP 7.3 to Makefile

- CHANGELOG.md
- library/Mockery/Generator/StringManipulation/Pass/InstanceMockPass.php
- library/Mockery/Mock.php
- tests/Mockery/ContainerTest.php
- tests/Mockery/Generator/StringManipulation/Pass/InstanceMockPassTest.php
Solved merge conflicts of PR #782.
Backport of PR #781 to Mockery 0.9
> Backport #781 (mock constructor) to mockery 0.9

- library/Mockery/Mock.php
> Bugfix: __isset call

- docs/reference/expectations.rst
Hi, noticed a wee mistake which might be confusing for some.
> Fix a typo

- .styleci.yml
- library/Mockery/Generator/StringManipulation/Pass/AvoidMethodClashPass.php
https://github.com/mockery/mockery/pull/1004#issuecomment-530729754
https://github.com/mockery/mockery/pull/1004#issuecomment-530788622
> disable braces fixer

- library/Mockery/Mock.php
Addresses https://github.com/mockery/mockery/issues/1057
> Fix type hint on shouldNotRecieve() argument

- library/Mockery/Mock.php
- tests/Mockery/MockClassWithIterableReturnTypeTest.php
> [1.4] Merge 1.3 in again

- CHANGELOG.md
~Pending https://github.com/mockery/mockery/pull/1079.~
---
After this PR is done, I'll do another merge up to 1.4 within a PR that "releases 1.4.1".
> [1.3] Release 1.3.2

- CHANGELOG.md
> Release 1.4.2

- CHANGELOG.md
~Let me test this with laravel/framework before I unmark it as WIP.~ EDIT: worked a treat.
> Release 1.3.3

- docs/reference/expectations.rst
> Issue #1176 Add docs on multiple call expectations

- CHANGELOG.md
> Merge 1.3 up into master branch

- composer.json
This patch includes the following changes:
- Update `composer.json` to use psr-4
> Switch to PSR-4 autoload

- .github/workflows/tests.yml
This pull request updates `nick-invision/retry` from v1 to v2.
> Bump `nick-invision/retry` to v2

- CHANGELOG.md
* https://github.com/mockery/mockery/pull/1192
* https://github.com/mockery/mockery/pull/1196
* https://github.com/mockery/mockery/pull/1199
* https://github.com/mockery/mockery/pull/1205
* https://github.com/mockery/mockery/pull/1208
* https://github.com/mockery/mockery/pull/1210
* https://github.com/mockery/mockery/pull/1212
* https://github.com/mockery/mockery/pull/1216
* https://github.com/mockery/mockery/pull/1217
* https://github.com/mockery/mockery/pull/1218
* https://github.com/mockery/mockery/pull/1222
* https://github.com/mockery/mockery/pull/1225
* https://github.com/mockery/mockery/pull/1226
* https://github.com/mockery/mockery/pull/1230
* https://github.com/mockery/mockery/pull/1232
* https://github.com/mockery/mockery/pull/1233
* https://github.com/mockery/mockery/pull/1234 …
> Changelog v1.6.0

- .github/workflows/codecov.yml
- .github/workflows/psalm.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- composer.json
- composer.lock
- psalm-baseline.xml
- psalm.xml.dist
> Removed support for PHP 8.0 and lower

- composer.json
> corrects php version constraint

- composer.json
> Update composer branch alias

- CHANGELOG.md
- psalm-baseline.xml
* https://github.com/mockery/mockery/pull/1262
* https://github.com/mockery/mockery/pull/1272
* https://github.com/mockery/mockery/pull/1270
* https://github.com/mockery/mockery/pull/1271
* https://github.com/mockery/mockery/pull/1274
* https://github.com/mockery/mockery/pull/1275
* https://github.com/mockery/mockery/pull/1276
**Full Changelog**: https://github.com/mockery/mockery/compare/1.6.1...1.6.2
> Changelog v1.6.2

- composer.json
- composer.lock
- psalm-baseline.xml
This patch updates `vimeo/psalm` from `5.9.0` to `5.12.0` via composer.
> Bump `vimeo/psalm` from `5.9.0` to `5.12.0`

- COPYRIGHT.md
> Create `COPYRIGHT.md` file

- .github/workflows/psalm.yml
- composer.json
- composer.lock
- psalm-baseline.xml
This PR updates `psalm` to the latest version, the `psalm.yml` workflow to use `ramsey/composer-install`, A GitHub Action to streamline the installation of PHP dependencies with Composer.
> Update psalm configuration and workflow

- .github/workflows/codecov.yml
- .github/workflows/tests.yml
- composer.json
This PR updates the `codecov.yml` workflow to use `ramsey/composer-install`, A GitHub Action to streamline the installation of PHP dependencies with Composer.
> Update codecov workflow

- CHANGELOG.md
- #1304
- #1303
- #1302
- #1301
- #1298
- #1297
- #1294
- #1290
- #1288
- #1287
- #1286
- #1285
- #1283
- #1282
- #1279
> Changelog v1.6.3

- CHANGELOG.md
> Changelog v1.6.4

- composer.json
- composer.lock
- phpunit.xml.dist
- tests/Fixture/PHP83/ClassName.php
- tests/Fixture/PHP83/Classes.php
- tests/Fixture/PHP83/Enums.php
- tests/Fixture/PHP83/Interfaces.php
- tests/Fixture/PHP83/Traits.php
- tests/Mockery/RegExpCompatability.php
- tests/PHP83/Php83LanguageFeaturesTest.php
- tests/Unit/PHP83/Php83LanguageFeaturesTest.php
> Test PHP `8.3` language features

- library/Mockery/Reflector.php
- tests/Bootstrap.php
- tests/Mockery/ReflectorTest.php
- tests/Unit/PHP82/Php82LanguageFeaturesTest.php
> Type declaration for `iterable|object`

- CHANGELOG.md
- [#1325: Keep the file that caused an error for inspection](https://github.com/mockery/mockery/pull/1325)
- [#1324: Fix Regression - Replace `+` Array Union Operator with `array_merge`](https://github.com/mockery/mockery/pull/1324)
**Full Changelog**: https://github.com/mockery/mockery/compare/1.6.5...1.6.6
> Changelog v1.6.6

- tests/PHP80/Php80LanguageFeaturesTest.php
- tests/PHP81/Php81LanguageFeaturesTest.php
- tests/PHP82/Php82LanguageFeaturesTest.php
This patch resolves composer warning about test namespace.
> Fix test namespaces
