mockery/mockery

composer.json

Fixed typo in project description's word "succinct". Fixes padraic/mocker#413

Typo in project description.

---

library/Mockery/Adapter/Phpunit/MockeryTestCase.php

Otherwise, sometime phpunit will fail due to no tests being found in MockeryTestCase

TestCase should be abstract

---

library/Mockery/Adapter/Phpunit/TestListener.php

Fixes PHPUnit 4.4 incompatibility.
Tested on PHPUnit 4.4.5 and PHPUnit 3.7.28.

Add 'addRiskyTest' to maintain abstract class relationship in TestListener

---

library/Mockery.php
tests/Mockery/ExpectationTest.php

When an expectation is set for a string, but a null is passed instead,
make sure the argument is correctly formatted in the exception message
so we don't get an empty string printed where null should be.
Ended up chasing my tail a couple of times because of messages like `No matching handler found for Mockery_154_Foo::foo("")` :)

Format null argument correctly

---

library/Mockery.php
tests/Mockery/WithFormatterExpectationTest.php

Assuming the existing *intended* behaviour remains desired, then this resolves #416

Exclude static properties and methods differently when formatting objects.

---

.travis.yml
composer.json
travis/after_script.sh
travis/before_install.sh
travis/before_script.sh
travis/extra.ini
travis/install.sh
travis/script.sh

This does a few things:
* Extracts all the scripts out to separate bash scripts for easier editing.
* It uses the 5.3.3 build target to compile and use php-src master (i.e. PHP 7)
* Fixes the mongo and redis extension loading
* Adds a composer self-update where needed
* For the PHP 7 (aka 5.3.3) build, installs composer manually
* Code coverage and scrutinizer will now target PHP 5.6 (was 5.5)
* Move satooshi/php-coveralls from composer.json to travis composer require command
Note: A previous commit moved hhvm to allowed_failures so PRs can pass checks. The 5.3.3 (actually PHP 7) is currently not allowed to fail.

Cleanup Travis builds and implement PHP7 target

---

travis/before_install.sh

Minor optimisation to speed up the php7 build by not cloning the entire history.

Limit php-src clone to depth 1

---

library/Mockery/Mock.php

This isn't actually unused.
---
Reverts padraic/mockery#444

Revert "unused namespace removed"

---

tests/Mockery/MockTest.php

This test demonstrates an issue on hhvm when mocking instances of the base `Exception` class. I've not been able to figure out why it fails though
```
BadMethodCallException: Call to a member function mockery_getName() on a non-object (NULL)
/home/craig/dev/duncan3dc/mockery/library/Mockery/Container.php:473
/home/craig/dev/duncan3dc/mockery/library/Mockery/Container.php:221
/home/craig/dev/duncan3dc/mockery/library/Mockery.php:74
/home/craig/dev/duncan3dc/mockery/tests/Mockery/MockTest.php:141
```

Create a failing test for mocking an exception

---

library/Mockery/ExpectationDirector.php
tests/Mockery/ExpectationTest.php

Makes callback in ->with() be called only once per expectation

---

library/Mockery/Mock.php
library/Mockery/MockInterface.php

I stumbled upon this after upgrading PhpStorm to version 9 (early access program).
It does currently mark all calls to `shouldReceive` and `shouldNotReceive`  with the following warning:
> Method call uses 1 parameters, but method signature uses 0 parameters
Looking at the `MockInterface` is also somewhat confusing since it does not define any parameters whatsoever. I am not sure why this is the case but I believe making them explicit at the interface is the least confusing solution.

Add varargs to Mockinterface::shouldReceive and MockInterface::shouldNotReceive

---

library/Mockery.php
library/Mockery/Generator/StringManipulation/Pass/ClassPass.php

When you mock a class that does not exist, or can't be found by autoloading, Mockery creates a temporary file, so the class can be required. The clean-up was left to the OS.
This change registers the files to be cleaned-up on teardown by Mockery.
See issue #487.

Clean-up temporary files on teardown

---

library/Mockery/Expectation.php
library/Mockery/Generator/Method.php
library/Mockery/Generator/Parameter.php
library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
phpunit.xml.dist
tests/Mockery/MockingParameterAndReturnTypesTest.php

This PR adds support for scalar parameter types return types on mocked object methods while maintaining compatibility with older PHP versions.
If a return type is declared on a method and no return expectation has been provided for the mock method call, a return value is automatically generated based on the declared type. This includes creating a new mock object to return if necessary.

Add support for parameter and return types

---

library/Mockery/Expectation.php
library/Mockery/Mock.php
tests/Mockery/MockingParameterAndReturnTypesTest.php

This PR addresses #490 by creating a mock return value when `shouldIgnoreMissing()` is called on the mock object and subsequently a method is called on the mock without setting expectations.

Mock return types on spies

---

.styleci.yml
library/Mockery/Mock.php

For now, StyleCI enforces PHP 5.6 compatible syntax. PHP 7 support is coming soon.

Fix StyleCI

---

docs/reference/startup_methods.rst

The method name is passed as a string: `$mock->shouldReceive('method_name')`

Added missing quotes to a parameter

---

library/Mockery/Instantiator.php

Fixes #512:
A fatal error is triggered when an exception occurs during instantiation using unserialisation:
> PHP Fatal error: Cannot use Exception as Exception because the name is already in use
Runtime: PHP 5.6.14-1+deb.sury.org~trusty+1 with Xdebug 2.3.2
The cause of this error is that \Exception is imported as Exception in \Mockery\Instantiator, while a class name Exception already exists in that namespace (\Mockery\Exception).
This commit fixes the name collision. I don't quite remember how I got a error to trigger during unserialisation, so there's no regression test.

Prevent trigger of error when exception occurs during unserialisation

---

README.md

Also for consistency with [Installation guide](https://github.com/padraic/mockery/blob/master/docs/getting_started/installation.rst).

Add to "require-dev" instead of "require" in composer.json

---

library/Mockery/Container.php
tests/Mockery/ContainerTest.php
tests/Mockery/MockTest.php

This PR is attempting to fix #472. While Mockery gets a parse error with `Mockery::mock('this-is-invalid')` this fix throws a Mockery\Exception error with friendlier message. It uses [the regex on the official document](http://php.net/manual/en/language.oop5.basic.php) and I'm assuming that namespaces follow the same rule.
It might be a little too strict since it currently allows a parameter like `mock('\\\\Foo')`. Please let me know if there's any better way.

fix #472 throw exception if given class name is invalid

---

.scrutinizer.yml
CONTRIBUTING.md
tests/Bootstrap.php

The "--dev" option of the `composer install` command is deprecated and it shows a warning message when you use it. In this way, I've removed every occurrence of this options that I've found in the project:
- Contribution guidelines
- Exception messages
- Code comments
- Scrutinizer config file

Removed "--dev" option from composer install command

---

CHANGELOG.md
docs/reference/argument_validation.rst
docs/reference/expectations.rst
library/Mockery/Expectation.php
library/Mockery/Matcher/MultiArgumentClosure.php
tests/Mockery/ContainerTest.php
tests/Mockery/ExpectationTest.php

This PR adds the new functionality requested in #459 . In this way, from now on it is possible to pass a closure to `withArgs()` method in order to validate a list of arguments at once. All the arguments passed in the call to the expected method will be passed to the closure, and if it evaluates to true, then the list of
arguments is assumed to have matched the expectation.

Added new functionality to support `withArgs($closure)`to validate a list of arguments at once

---

library/Mockery/Expectation.php
tests/Mockery/ExpectationTest.php

Hi,
I think that aliases for booleans are more readable in tests. 
How about that ?

Aliases expectation for boolean values

---

library/Mockery/Adapter/Phpunit/TestListener.php
library/Mockery/Expectation.php
library/Mockery/Matcher/MultiArgumentClosure.php
tests/Mockery/ExpectationTest.php
tests/Mockery/MockeryCanMockMultipleInterfacesWhichOverlapTest.php

Fixing [#549](https://github.com/padraic/mockery/issues/549) issue.

Throwing an exception when times() receives a non integer value as it's parameter.

---

tests/Bootstrap.php

Composer allows the `COMPOSER_VENDOR_DIR` environmental variable (https://getcomposer.org/doc/03-cli.md#composer-vendor-dir) to be set; if it is, it installs dependencies in that directory instead of in `vendor`. However `Bootstrap.php` will still look for dependencies and `autoload.php` in the `vendor` directory, and will not find it there.

respect COMPOSER_VENDOR_DIRECTORY envar

---

library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
tests/Mockery/DummyClasses/Namespaced.php
tests/Mockery/NamedMockTest.php

Fixing issue [#557](https://github.com/padraic/mockery/issues/557).
Notes on the changes:
I've created a new file to include classes that are going to be used as dummy inside the tests. I've done this because I needed to use different namespaces, and to be able to do that, I needed to include a file called `Namespaced.php`.
In `MethodDefinitionPass.php` at line 86, I've created an array to hold the TypeHints to be used in the method definition. The problem with this is that the code is not maintainable neither reusable. I  researched in the project for similar arrays, and I found at least three uses of those in the following files:
* `MockConfigurationBuilder` at line 9 
* `KeywordPatch` at line 66. 
I suggest to put those arrays in a `functions.php` file or any other file that can make …

Fixing issue #557

---

library/Mockery/Mock.php
tests/Mockery/SpyTest.php

Solving [issue 440](https://github.com/padraic/mockery/issues/440).
Notes about changes:
- This solution merely adds a protected count property used while retrieving expectation counts.
- The property is then incremented when shouldHaveReceived and it's opposite are called.
The problems with this solution: 
- We're not treating the count in the expected framework's way:
- Adding the VerificationDirector, using the method `mockery_setExpectationsFor` within `Mock.php`.
- Retrieve the count inside the iteration on line 489 of the same file.
- It's not possible to get the VerificationDirector using the mockery_getExpectationsFor method in `Mock.php`.
- It's not possible to find an specific expectation using `mockery_findExpectation` method on line 529 in `Mock.php`.
- All other methods that …

Resolving expectation count issue when using Spy related assertions.

---

library/Mockery/Mock.php
library/Mockery/MockInterface.php
tests/Mockery/ContainerTest.php
tests/Mockery/MockingProtectedMethodsTest.php

Fixing [issue 497](https://github.com/padraic/mockery/issues/497).
Notes about changes:
- I've changed the `mockery_getMethods` method in the `Mock` class. 
- The method now doesn't treat prototypes, it just lists the reflection methods of the current class.
- If there's a real reason for treating prototype methods, it's not being covered by the tests.
- I've changed the description of  an exception thrown when trying to mock a protected method, it's an attempt to be more accurate. The change can be seen in the `Mock.php` file, at line 207.
- I've removed unused commented code from `Mock` and `MockInterface` source.

Fixing increased visibility issue(497).

---

library/Mockery.php

Notes:
- Some methods still don't present some header description, when I get more time, this will be new a pull request. The same is true for other files that present this inconsistency.

Adding missing docblock comments to the methods on Mockery.php

---

library/Mockery.php

Notes about changes:
- Most of the comments are obvious descriptions of what the method does, but for purposes of getting docblocks into a pattern, I've added the lacking ones.

Adding explanatory comments to the docblocks that were missing it on Mockery.php.

---

examples/starship/StarshipTest.php

Now, this test does not fail even if I change test case like below.
So I think it is better to update the example.
```php
//does not fail even if call once
$mock->shouldReceive('disengageWarp')->never()->ordered();
```

Update example to call mockery close

---

library/Mockery/Mock.php
tests/Mockery/ExpectationTest.php

Fixes [issue #475](https://github.com/padraic/mockery/issues/475).

Adding specific message when calling method without any expectations on mock.

---

library/Mockery/Container.php
tests/Mockery/MockTest.php

This makes the test introduced in https://github.com/padraic/mockery/pull/456/files pass under hhvm and adds a test for mocking subclasses of Exception.

allow mocking exceptions under hhvm

---

library/Mockery/Mock.php
tests/Mockery/ExpectationTest.php

Fixes [issue #529](https://github.com/padraic/mockery/issues/529).
Notes about changes:
- `mockery_isAnonymous` now checks if the current mock implements more interfaces rather than implementing only the `Mock` one.
- If, at some day, Mock start to implement more interfaces, this check will fail and will need to be corrected.
Suggestions:
- The Exception thrown when mocking non existent methods should be more specific, maybe with only a name specifying the situation.

Mock's mockery_isAnonymous method now checks against implemented interfaces.

---

library/Mockery.php

When multiple unit tests are run without process isolation, \Mockery::close will attempt to unlink files from the _filesToCleanUp array every time.
This patch will clear the _filesToCleanUp array after the unlink loop, so no new attempts will be made to clean up files which don't exist anymore anyway.

Clear the _filesToCleanUp array after unlink.

---

library/Mockery/Mock.php
tests/Mockery/MockClassWithMethodOverloadingTest.php

I confirmed #564 with php 5.6.20 & xdebug. It says:
```
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /Users/nobu/projects/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code on line 340
```
In the Mockery_0_test_Mockery_TestWithMethodOverloading:
```php
public function __call($method, $args) // line 340
{
return $this->_mockery_handleMethodCall($method, $args);
}
```
This pull request attempts to avoid calling non-existing method infinitely and throws `BadMethodCallException` as the document says. Hope it helps.

Fix segfaults with a mocking class with __call

---

library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
tests/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPassTest.php

This is just a small refactor, instead of checking against classes, I've added the interface(`TargetClassInterface`) as the type hint. Changes on `getMagicMethods()`, within `MagicMethodTypeHintsPass`.

Adding TypeHint to getMagicMethods(), on MagicMethodTypeHintsPass.

---

library/Mockery/Expectation.php
library/Mockery/Generator/Method.php
library/Mockery/Generator/Parameter.php
library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
phpunit.xml.dist
tests/Mockery/MockeryCanMockMultipleInterfacesWhichOverlapTest.php
tests/Mockery/MockingParameterAndReturnTypesTest.php

[This pull request](https://github.com/padraic/mockery/commit/3dd65d5181a3ffe4e5e406e7725928358e5967c7) adds support for PHP 7's scalar typehints and return type declarations. This PR adds that functionality to `0.9.x`. The changes seem to be backwards compatible as far as I can tell, so tagging either a new `0.9.5` or a `0.10.0` would be acceptable per SemVer.
This addresses: #561 (and, I think, #499)

Backport commits for PHP 7 support

---

.styleci.yml

Sorry this file can't be fixed by StyleCI right now. We do hope to fix that soon, but in the meanwhile, this should be suffice.

Exclude SemiReservedWordsAsMethods.php on StyleCI

---

library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
tests/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPassTest.php

`__toString` was not detected but `__tostring` was instead.
The test class was written was using the latter as well.

Updated the Magic Pass to use the proper standard for toString

---

composer.json

Use PRETTY_PRINT syntax and reorder keywords - avoid commit noise when adding/updating a keyword

Use PRETTY_PRINT syntax and reorder keywords

---

docs/conf.py

This lines enable the php highlighting to the `code-block`s when the code doesn't start with `<?php`

[Docs] Enable php highlighting to php code

---

library/Mockery/Instantiator.php

The bugfix in #513 was not pushed to the 0.9 branch. I think it's an important fix, so I'm proposing it be backported.

Backports #513 to 0.9 branch

---

composer.json

Use a stable version (2.0+) of `hamcrest/hamcrest-php` instead of `dev-master`

stable hamcrest/hamcrest-php

---

library/Mockery/Container.php
tests/Mockery/ExpectationTest.php

Currently when Mockery has been configured not to allow mocking non-existent methods, attempting to mock a non-existent class gives a confusing error. It complains that it can't mock methods that don't exist on the specified class, but actually the error is that mockery can't find the referenced class to mock it and verify the methods it's allowed to mock.
This commit changes that behaviour so that attempting to mock a class that doesn't exist throws an exception that explicitly says that the specified class doesn't exist, however it only does so while mockery is configured not to allow mocking of non-existent methods.
I'm not entirely certain that this is the right way to make this change, so feedback is appreciated. Also appreciated is feedback on if this change is considered desirable; …

Raise a descriptive error when a required class is missing

---

CHANGELOG.md
docs/reference/phpunit_integration.rst
library/Mockery/Adapter/Phpunit/TestListener.php
tests/Mockery/Adapter/Phpunit/TestListenerTest.php

The listener has been removed in ede143167ae34e because it is called too
late in the test lifecycle. This marks tests incorrectly as risky, if
there are no other assertions in the test.
Simply removing the listener silently breaks existing testsuites for
PHPUnit <5.5.6, which will not complain about missing listeners.
The listener added in this commit will no longer verify mock assertions.
Instead, the listener will mark tests as failed if they don't verify the
mock assertions themselves.
This will surface the change for existing users of the listener and help them
migrate to the trait or base class. Is also serves as an opt-in safefail for
new Mockery users.
This is how it looks in action:
```
$ bin/phpunit 
PHPUnit 5.3.5 by Sebastian Bergmann and contributors.
...........F
Time: 595 ms, …
```

Restore the PHPUnit listener

---

docs/reference/phpunit_integration.rst

Old namespace made errors during running tests.

Change namespace into correct form

---

library/Mockery/Expectation.php

Simplest way I could think of of fixing #645 .

Fix withNoArgs() to work with PHP 7.2

---

library/Mockery/Generator/Method.php
tests/Mockery/Fixtures/MethodWithNullableReturnType.php
tests/Mockery/MockingNullableMethodsTest.php

Allow mocking nullable return types for 7.1

---

library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
tests/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPassTest.php

Resolves #661 
Just expanded on the work done in #585 by making sure that MagicMethodTypeHintsPass looks at interfaces as well as the class and modifying the tests to look at both the class and the interface cases.

Apply MagicMethodTypeHintsPass to interfaces

---

library/Mockery/ExpectationBuilder.php
library/Mockery/HigherOrderMessage.php
library/Mockery/Mock.php
library/Mockery/MockInterface.php

Not sure what people think about this, it just gets away from using strings for method names...
``` php
$mock->shouldReceive()->foo("bar")->andReturn(123);
```

Alternative shouldReceive syntax

---

tests/Mockery/ExpectationTest.php

One test was not passing because of a deprecation warning on PHPUnit's old `getMock()` method.

Fixed PHPUnit deprecation warning

---

.travis.yml

This also fixes an issue where the extensions were still being installed in PHP 7.1 builds, causing errors.

Improved Travis extension setup code

---

CHANGELOG.md
README.md
library/Mockery.php
library/Mockery/CompositeExpectation.php
library/Mockery/Expectation.php
library/Mockery/ExpectationInterface.php
library/Mockery/ExpectsHigherOrderMessage.php
library/Mockery/Generator/StringManipulation/Pass/AvoidMethodClashPass.php
library/Mockery/Generator/StringManipulationGenerator.php
library/Mockery/HigherOrderMessage.php
library/Mockery/Mock.php
tests/Mockery/AllowsExpectsSyntaxTest.php

Further to #598 
``` php
<?php
// old
$mock->shouldReceive("foo")->with(123)->andReturn(true)->once();
// or
$mock->shouldReceive()->foo(123)->andReturn(true)->once();
// new
$mock->expects()->foo(123)->andReturns(true);
```
``` php
<?php
// old
$stub->shouldReceive("foo")->with(123)->andReturn(true);
// or
$stub->shouldReceive()->foo(123)->andReturn(true);
// new
$stub->allows()->foo(123)->andReturns(true);
```
Despite the new methods on the mocks, this is fully BC as they are skipped if the class to be mocked contains matching methods.
I personally prefer this syntax, but I haven't put it to much use. It's always bothered me that `shouldReceive()` starts with `should`, when it doesn't actually form a mock expectation without the additional call to `->once()` or one of the other count …

allows() and expects() syntax

---

library/Mockery/Expectation.php
tests/Mockery/Fixtures/MethodWithNullableReturnType.php
tests/Mockery/MockingNullableMethodsTest.php

Forces the return value to null

---

CHANGELOG.md
docs/reference/argument_validation.rst
library/Mockery/Matcher/MustBe.php

This matcher is ambiguous at best, better alternatives are available in PHPUnit and Hamcrest.
Related to #537, #536, #328

Deprecates MustBe matcher

---

library/Mockery/Expectation.php
tests/Mockery/Fixtures/VoidMethod.php
tests/Mockery/MockingVoidMethodsTest.php

Fixes `void` support that I've tried to add on #693

Fix void support

---

library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php
library/Mockery/Adapter/Phpunit/MockeryTestCase.php

Consolidates trait and dynamically extend PHPUnit

---

library/Mockery/Mock.php

I was doing some profiling and found that 15% of all of our test time was taken in `uniqid`. This removes the usage of uniqid because it should not be truly needed. This caused this part of the code to go from taking 97 seconds to taking 0.2 seconds.
Note: Our tests are making 50k calls to `hasMethodOverloadingInParentClass`, via `_mockery_handleMethodCall` 
This is also when run on HHVM 3.14.5. Mainline PHP may or may not have a faster implementation.

Fixing performance issue with uniqid

---

library/Mockery.php
library/Mockery/CompositeExpectation.php
library/Mockery/Container.php
library/Mockery/Expectation.php
library/Mockery/Mock.php
library/Mockery/MockInterface.php
library/Mockery/VerificationDirector.php
library/helpers.php
tests/Mockery/ContainerTest.php

Methods like "shouldReceive" may receive an arbitrary number of arguments. Yet according to the methods' signature no arguments are allowed. So many IDEs like PHPStorm assume a bug when the method is used as intended. The solution to this problem are variadic parameters, which are available since php5.6. I assume that at least 5.6 is required for the current master of Mockery. If 5.6 is the minimum requirement of the current stable version as well I will provide a patch for that version, too.

replacing func_get_args with variadic parameters for better IDE-support

---

library/Mockery/Generator/Parameter.php
tests/Mockery/Fixtures/MethodWithNullableParameters.php
tests/Mockery/MockingMethodsWithNullableParametersTest.php

This PR adds support for nullable types on parameters.

Support nullable parameters

---

library/Mockery.php
tests/Mockery/ExpectationTest.php

Fixes #697 
I don't think it's a good idea to use `__toString` for arbitrary objects for now as we really can't guarantee a reasonable error message if we do so. Going forward, I plan to use sebastianbergmann/comparator or possibly just it's dependencies to provide better output.

Uses a MatcherAbstracts string form in error output

---

library/Mockery/ExpectationInterface.php

Problem: PhpStorm not always can follow to __call method and inspector may yell that it can not find method.
Solution: Add PHPDoc with methods descriptions

PhpStorm and magic __call methods

---

library/Mockery/Expectation.php

PHP 7.2 introduces a warning when you try to count something that isn't countable. Sometimes `$this->_expectedArgs` is null:
```
count(): Parameter must be an array or an object that implements Countable
/tmp/vendor/mockery/mockery/library/Mockery/Expectation.php:313
/tmp/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:173
/tmp/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:138
/tmp/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:91
/tmp/test.php:7
```

Avoid warnings in PHP 7.2 from count()

---

CHANGELOG.md
docs/reference/startup_methods.rst
library/Mockery/Mock.php
tests/Mockery/MockingNullableMethodsTest.php

- Fix + related test
- Documented BC BREAK on changelog
- Added a bit of documentation on how default return types work for mocks related to methods with return types

Spies return `null` by default from ignored (non-mocked) methods with nullable return type

---

.travis.yml
composer.json
library/Mockery/Exception/InvalidArgumentException.php
library/Mockery/Matcher/PHPUnitConstraint.php
phpunit.xml.dist
tests/Mockery/Adapter/Phpunit/TestListenerTest.php
tests/Mockery/AdhocTest.php
tests/Mockery/AllowsExpectsSyntaxTest.php
tests/Mockery/ContainerTest.php
tests/Mockery/ExpectationTest.php
tests/Mockery/Generator/DefinedTargetClassTest.php
tests/Mockery/Generator/MockConfigurationTest.php
tests/Mockery/Generator/StringManipulation/Pass/CallTypeHintPassTest.php
tests/Mockery/Generator/StringManipulation/Pass/ClassNamePassTest.php
tests/Mockery/Generator/StringManipulation/Pass/InstanceMockPassTest.php
tests/Mockery/Generator/StringManipulation/Pass/InterfacePassTest.php
tests/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPassTest.php
tests/Mockery/GlobalHelpersTest.php
tests/Mockery/Loader/LoaderTestCase.php
tests/Mockery/Matcher/PHPUnitConstraintTest.php
tests/Mockery/MockTest.php
tests/Mockery/MockeryCanMockClassesWithSemiReservedWordsTest.php
tests/Mockery/SpyTest.php
tests/Mockery/Test/Generator/MockConfigurationBuilderTest.php
tests/Mockery/WithFormatterExpectationTest.php

Initial run through of changes for #728. The main areas needing attention:
* PHPUnitConstraint - Incompatible between PHPUnit 5 and 6 as the referred to typehints and such are not part of the PHPUnit 5 forward compatibility shim.
* Deprecation error under PHP 7.0 (on one test where constructor shares class name).
* Numerous reports related "risky tests" under PHPUnit 6.0 though presumably that's all down to test framework in place which needs to be updated.
* The Listener is also incompatible with PHPUnit 6 (typehints again).

[WIP] PHPUnit 6 Support

---

CHANGELOG.md
library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php

PHPUnit calls assertPostConditions only on passing test cases,
which causes Mockery to not get closed on failing test cases.
This solution, originally provided by @davedevelopment uses
the @before and @after annotations to teardown the Mockery container
for the failing test cases.
Fixes #639

Teardown Mockery on failed test cases

---

CHANGELOG.md
library/Mockery.php
library/Mockery/Expectation.php
library/Mockery/Matcher/Pattern.php
tests/Mockery/ExpectationTest.php

Stop trying to do implicit regex matching when matching
string arguments, as it tends to not play nicely with
JSON strings as arguments - PHP thinks it's a regex pattern
to match against.
Introduce \Mockery::pattern() and the Pattern matcher to do
explicit regex pattern matching when it's required by the user.
Fixes #338

Add explicit pattern matcher

---

CHANGELOG.md
library/Mockery.php

While extracting getters for objects is a nice idea in theory,
in practice the whole idea of calling random get* and is* methods
on objects can backfire, because we can actually hide, or even worse,
accidentally cause calling methods that shouldn't be called in the
first place.
Fixes #619

Don't extract getters of objects

---

CHANGELOG.md
library/Mockery/Expectation.php
tests/Mockery/ContainerTest.php

When setting values for properties, don't set them just on
the current mock, but set them on all the related mocks that
are in the container.
This way the overloaded instance mocks will get the properties
set, just as the mock itself.
Fixes #451

Set property values on all related mocks

---

library/Mockery/Expectation.php
tests/Mockery/AllowsExpectsSyntaxTest.php

Keep track of count validators as an associative array,
so we can easily override existing validator classes with
new validators of the same type.
This allows to modify the number of call expectation, especially
when working with ``expects()``, because it defines ``once()``
by default.
Fixes #745

Allow overriding count validators

---

docs/reference/argument_validation.rst

The condition was checking for `$arg` which is undefined and should have been checking for `argument`

Doc Fix invalid code for closure

---

library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
tests/Mockery/MockingInternalModuleClassWithOptionalParameterByReference.php
tests/Mockery/MockingInternalModuleClassWithOptionalParameterByReferenceTest.php
travis/extra.ini

This will fix issue: https://github.com/mockery/mockery/issues/757, which describes, that Mockery will actually fail to create proper code, when overriding the parameter map with optional parameters passed by reference, e.g. [Memcache::get()](http://php.net/manual/en/memcache.get.php).

Fix: internal class param by reference cannot have default value

---

library/Mockery.php
library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php
tests/Mockery/ContainerTest.php
tests/Mockery/ExpectationTest.php
tests/Mockery/HamcrestExpectationTest.php
tests/Mockery/MockClassWithMethodOverloadingTest.php
tests/Mockery/MockClassWithUnknownTypeHintTest.php
tests/Mockery/MockTest.php
tests/Mockery/MockingMethodsWithIterableTypeHintsTest.php
tests/Mockery/MockingMethodsWithNullableParametersTest.php
tests/Mockery/MockingNullableMethodsTest.php
tests/Mockery/MockingParameterAndReturnTypesTest.php
tests/Mockery/MockingProtectedMethodsTest.php
tests/Mockery/MockingVariadicArgumentsTest.php
tests/Mockery/MockingVoidMethodsTest.php
tests/Mockery/SpyTest.php

Kinda...
This moves nearly all of the tests away from an isolated container. This loses some niceness in the tests, but allows us to use our own PHPUnit integration to achieve assertion counting etc.
The confusing tests are the ones where we want the actual test to throw one of our exceptions, so we have to manually call `Mockery::close()` to force it as part of the test, rather than the PHPUnit integration firing them in the postAssertion hook.
There are a lot of tests that have been added for bugs and special cases, which aren't all that clear. I've left them alone, only adding the odd assertion to make them go green rather than yellow. I'd rather have the odd bit of confusion for an individual test, than newcomers to the project run the suite and see loads of risky tests.

Fixes all risky tests

---

library/Mockery/Expectation.php

On PHP 7.2 count throws a warning when passing something that isn't an array or a implementation of Countable to the count function.
``` _expectedArgs ``` may be null sometimes, this causes [tests to fail](https://travis-ci.org/laravel/framework/jobs/257748808) on 7.2.

Cast expectedArgs to array (fix php7.2)

---

library/Mockery/CountValidator/Exact.php
library/Mockery/Expectation.php
library/Mockery/ExpectationInterface.php
tests/Mockery/ExpectationTest.php

Adds functionality for #264 
```php
// Add a message which will be displayed in the exception message
$mock->shouldReceive('foo')->once()->because('We like foo');
```

Set the InvalidCountException message using because($message);

---

docs/reference/alternative_should_receive_syntax.rst

Allows apparently does not allow to define multiple
return values for subsequent calls to the same method.
Not sure where I got this from the first time around I
wrote these docs?
Fixes #788

allows does not allow multiple return values

---

library/Mockery/Mock.php
tests/Mockery/AllowsExpectsSyntaxTest.php

What do we think?
I personally prefer to avoid the string names, but this makes the API more like the old API, at the slight cost of confusing return types for the `allows` and `expects` methods, although the `allows` already has mixed return thanks to the array of stubs functionality.

Allows use of string method names in allows and expects

---

library/Mockery/Mock.php
tests/Mockery/Fixtures/ClassWithAllLowerCaseMethod.php
tests/Mockery/MockingAllLowerCasedMethodsTest.php

PHP method calls are case insensitive, so have Mockery search
for a handler in a case insensitive way, if needed.
This usually happens with PHP extensions, when the docs say one
thing (camelCasedMethod), but the C implementation is different
(camelcasedmethod).
Fixes #800

Search for handlers in a case instensitive way

---

CHANGELOG.md
docs/cookbook/class_constants.rst
docs/getting_started/upgrading.rst
docs/reference/spies.rst

Hi
Here are some minor improvements to the spelling in the documentation

Fix Spelling in Documentation

---

library/Mockery/Adapter/Phpunit/TestListener.php
tests/Mockery/Adapter/Phpunit/TestListenerTest.php

Using mockery 1.0-dev we get a lot of warnings and [risky tests](https://github.com/mockery/mockery/issues/742) this PR fixes the issue.
In Mockery.php on line 163 there's an `@unlink` which phpunit warns about if xdebug is enabled.
```
unlink() used in /Users/marijn/my-project/vendor/mockery/mockery/library/Mockery.php:163
```
To fix this you can add Mockery to the Blacklist in phpunit so it's ignored and tests are no longer marked risky because of this `@unlink`.
--
Maybe there is a better way/place to put this, as I read that the Listener is kind of deprecated in version 6.  But I couldn't find a better place. As the Listener allows you to do it `onSuiteStart` which is better than always doing it `onTestStart`.
The Listener also makes the user aware in case you don't call …

Fix risky tests

---

library/Mockery/Adapter/Phpunit/TestListener.php
tests/Mockery/Adapter/Phpunit/TestListenerTest.php

Apologies, I'm not sure where it went wrong, but the [previous PR](https://github.com/mockery/mockery/pull/769) had the wrong namespace. 
This fixes the namespace and test to use the correct one.

Fix namespace in TestListener

---

library/Mockery/Matcher/MustBe.php
library/Mockery/Mock.php

I've removed the `else`s when we have already returned something :put_litter_in_its_place:

Clean elses

---

tests/Mockery/AdhocTest.php
tests/Mockery/ContainerTest.php
tests/Mockery/ExpectationTest.php
tests/Mockery/Generator/MockConfigurationBuilderTest.php
tests/Mockery/Generator/MockConfigurationTest.php
tests/Mockery/MockingMethodsWithIterableTypeHintsTest.php
tests/Mockery/MockingMethodsWithNullableParametersTest.php
tests/Mockery/MockingParameterAndReturnTypesTest.php
tests/Mockery/MockingVoidMethodsTest.php
tests/Mockery/NamedMockTest.php

I've refactored more tests, like #815, this time using:
- `assertInstanceOf` and `assertNotInstanceOf` instead of `instanceof` operator and `get_class` function;
- `assertArrayHasKey` and `assertArrayNotHasKey` instead of `array_key_exists` and `isset` function;
- `assertLessThan` for mathematical comparisons;
- `assertCount` instead of `count` function;
- `assertInternalType` instead of `is_callable` function.

Refactoring tests

---

composer.json

I've bumped `PHPUnit 6` version. This will help us test `PHP 7.2` in #814

Bump PHPUnit 6 version

---

library/Mockery/Mock.php

Sorry for the unsolicited PR.
I just had a test error from trying to mock a protected method. I thought it might be useful if the message explained how to enable mocking protected methods on the mock object. It seems like if a developer is getting the error message then there's a good chance they want to mock the protected method.

Updated protected method mocking exception message

---

library/Mockery.php
library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php
library/Mockery/CompositeExpectation.php
library/Mockery/Configuration.php
library/Mockery/Container.php
library/Mockery/Expectation.php
library/Mockery/ExpectationDirector.php
library/Mockery/ExpectationInterface.php
library/Mockery/ExpectsHigherOrderMessage.php
library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
library/Mockery/Generator/TargetClassInterface.php
library/Mockery/Matcher/PHPUnitConstraint.php
library/Mockery/Mock.php
library/Mockery/MockInterface.php
tests/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegrationTest.php

Some fixes found with [`PHPStan`](https://github.com/phpstan/phpstan). Noticeable changes:
- `__construct` does not return anything;
- Fix [documentation of variadic parameters](https://github.com/phpstan/phpstan/issues/683#issuecomment-350254607);
- PHPUnit's `markAsRisky` [does not take any argument](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php#L693).

Fixes from PHPStan

---

library/Mockery/ExpectationInterface.php
library/Mockery/Mock.php
library/Mockery/MockInterface.php

Some methods contain phpdoc with return type of `ExpectationInterface`, but this interface contains only a very limited set of methods compared to the actual implementation in `Expectation`. This cases various problems with autocompletion in IDEs.
A previous attempt to solve this used `@method` annotations on `ExpectationInterface`, but this approach did not cover all the necessary methods, and furthermore is simply wrong - either every implementor supports all the methods and they should be defined in PHP code of the interface, or they don't in which case additional `@method` annotations are wrong.

Fix PHPdoc

---

Makefile

This way it's more obvious that a target will no result in creating a
file or directory also a single list tends to get out of date

Explicitely marks each target as PHONY

---

Makefile

Makes `composer.json` a pre requisite of vendor, this is way `vendor` will be updated when `composer.json` is updated (useful if you run it locally)

Vendor should be updated if composer.json changes

---

.gitignore
.travis.yml
composer.json

Automatically publish php docs to gh-pages. For this to work you will need to able gh-pages and configure it for the `gh-pages` branch.
You will also need to add an environment var to travis called `GITHUB_TOKEN` with your GitHub token (see https://docs.travis-ci.com/user/deployment/pages/). 
Finally, this does not provide a fully comprehensive overview of the API(there are docblocks missing, and phpdocumentor will yell about this in the "Errors" report with ~500 notices). But over time I'm sure that could be PR'd back in separately.

Publish API Documentation to GH Pages

---

library/Mockery.php
library/Mockery/Expectation.php
library/Mockery/Matcher/AndAnyOther.php
library/Mockery/Matcher/AndAnyOtherArgs.php
library/helpers.php
tests/Mockery/ExpectationTest.php

The name is on purpose "andAnyOther" so that it
is visible from the name itself that it should
never be the first matcher in a list of matchers,
and hopefuly the "other" part says enough that
it will match more than one argument.

Adds andAnyOther argument matcher

---

phpunit.xml.dist
tests/Mockery/ContainerTest.php
tests/Mockery/MockingOldStyleConstructorTest.php

So we run it only against PHP 5.6 as it is deprecated
as of PHP 7.

Move OldStyleConstructor test to a separate file

---

library/Mockery/Mock.php

Fix typo on the return annotation of shouldNotReceive

---

library/Mockery/Generator/MockConfiguration.php

HHVM has a [built-in decorator](https://docs.hhvm.com/hack/attributes/special#__memoize) that memoizes class methods. However, its implementation is incompatible with the code generation/evaluation strategy that Mockery uses.
This PR fixes Mockery to allow mocking of classes that use the decorator, though with the caveat that the decorator will no longer function as advertised. This is regrettable, but memoization (as implemented by HHVM) is solely a means of improving performance, and so disabling it in tests should not greatly affect behavior.

Fix mocking with classes that use HHVM memoization

---

library/Mockery.php
library/Mockery/ClosureWrapper.php
library/Mockery/Mock.php
library/Mockery/MockInterface.php
tests/Mockery/CallableSpyTest.php

Here's a take on the request in #711
``` php
$spy = spy(function($n) { return $n + 1;});
array_map($spy, [1, 2]); // [2, 3]
$spy->shouldHaveBeenCalled();
$spy->shouldHaveBeenCalled()->twice();
$spy->shouldHaveBeenCalled()->with(1)->once();
$spy->shouldHaveBeenCalled()->with(2)->once();
$spy->shouldHaveBeenCalled()->with(3); // throws...
```

RFC: Callable spies

---

.phpstorm.meta.php
library/helpers.php

I saw a previous attempt at this was made in #759, but it looks like @wan2land hasn't got around to creating a new PR based on the new format for PhpStorm metadata.
This PR is basically the same thing as #759, but using the new format.
For reference, [here is the documentation about this feature in PhpStorm](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata)

Add PhpStorm Advanced Metadata for autocompletion

---

.gitignore
Makefile
composer.json

See https://github.com/phpDocumentor/phpDocumentor2/issues/1914
Using the phar to avoid having to depend of dev versions of
phpDocumentor and it's dependencies in composer json

Switches to an alpha version of phpDocumentor

---

.styleci.yml
library/Mockery/Generator/Method.php
tests/Mockery/Fixtures/MethodWithHHVMReturnType.php
tests/Mockery/MockingHHVMMethodsTest.php

Return type cannot be properly evaluated by PHP `eval()` function. Stripping out the following return type: `tuple`, `array<*>` or anything with `<*>` in it, `HH\void`, `HH\this`, `HH\ImmVector`, `HH\ImmMap`, `HH\ImmSet`.
The hope is HHVM have a replacement for `eval`. If not, this seems to be the best course forward

Upgrading to HHVM 3.25 causes errors due to return type

---

library/Mockery/MockInterface.php

According to `MockInterface` the first argument of `shouldHaveReceived()` is required, whereas it can be used with no parameter.
Fix #894.

Fix shouldHaveReceived parameters declaration

---

library/Mockery/Generator/Method.php
library/Mockery/Generator/StringManipulation/Pass/ClassPass.php
tests/Mockery/Fixtures/MethodWithHHVMReturnType.php
tests/Mockery/Generator/StringManipulation/Pass/ClassPassTest.php

HHVM has type-constant `const type Example = ExampleClass` which allows custom return type  As a result, return type can be anything specified by the developer. Therefore, we strip all return type for HHVM.
Prevent Mockery from creating HH\this and other HH namespace class which already exists for HHVM.

Strip HHVM return type and prevent HH object creation

---

library/Mockery.php
library/helpers.php
tests/Mockery/GlobalHelpersTest.php

The legacy projects, or the packages, which are supporting an older PHP versions would be able to use the same code. The same static method `Mockery::globalHelpers()` and the same global helpers, for example `mock()`, for creating the mocks.

[0.9] The `Mockery:: globalHelpers()` added for the backwards compatibility

---

docs/reference/creating_test_doubles.rst

Maybe I am confused, but the identifier can be a class name, right? 🤔 
I mean, that's how you make it inherit that class - or am I misreading something and identifier is not the thing you pass to `\Mockery::mock`?

Fix in documentation of test doubles

---

library/Mockery.php
library/Mockery/Mock.php
library/Mockery/MockInterface.php

It's correct [here](https://github.com/mockery/mockery/blob/dc9255b24b028cb49fae09a8f46345f483114fff/library/Mockery/CompositeExpectation.php#L115) but not in these other two places.
Awesome project!

Change type of unpacked var

---

library/Mockery/Mock.php
tests/Mockery/MockTest.php

Fix #934 Allowing mocking of protected methods when `allowMockingNonExistentMethods` is set to `false` and `shouldAllowMockingProtectedMethods` is called.

Fix allowing mocking of protected methods when configured to not allow non existent methods

---

library/Mockery/Expectation.php
tests/Mockery/ContainerTest.php

When setting values for properties, don't set them just on
the current mock, but set them on all the related mocks that
are in the container.
This way the overloaded instance mocks will get the properties
set, just as the mock itself.
Fixes #451 in the 0.9 branch (for those who can't upgrade to PHP 5.6).

Set property values on all related mocks (0.9 branch)

---

CHANGELOG.md
library/Mockery/Adapter/Phpunit/Legacy/TestListenerTrait.php
library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegrationAssertPostConditionsForV7AndPrevious.php

The current combination of PHPUnit 5.7.27 with Mockery 1.2.1 cause fatal errors which are described in detail in #946. This PR addresses the two issues described in the aforementioned issue.
The commit messages will link to relevant sources and explain the proposed fixes in higher detail.

Provide PHP 5.6 / PHPUnit 5.7.27 support

---

library/Mockery/Generator/Parameter.php
tests/Mockery/Generator/ParameterTest.php

When mocking like this: 
```php
$guzzle = Mockery::mock('overload:'.GuzzleClient::class, ClientInterface::class);
```
I get the following error:
```php
Declaration of
GuzzleHttp\Client::send(GuzzleHttp\Psr\Http\Message\RequestInterface $request, array $options = Array)
must be compatible with
GuzzleHttp\ClientInterface::send(Psr\Http\Message\RequestInterface $request, array $options = Array)
```
Notice the first type hint begins with `GuzzleHttp\`. This is because the generator returns relative type hints, which is a bug. This PR fixes it by always return the absolute type hint.
I also added a unit test for this. The rest of the suite passes with this change.

Fix type hints in the generator to return an absolute class name

---

library/Mockery.php
library/Mockery/Generator/MockConfiguration.php
library/Mockery/Generator/MockNameBuilder.php
library/Mockery/Generator/UndefinedTargetClass.php
tests/Mockery/DemeterChainTest.php

The current implementation fails in the following situation:
```
$mock = \Mockery::mock(Order::class);
$mock->shouldReceive('getCustomer->getFirstName')->andReturn('John');
$mock->shouldReceive('getCustomer->getLastName')->andReturn('Doe');
```
In this case, if `getCustomer` has a type hint for return type, the mock for getLastName will not work. This happens because the named mock doesn't have the prefix `Mockery_<count>__`, so instead of `Mockery_1__demeter_02db565163e0992acfde42edfd58d833_getCustomer`, it will be named only `demeter_02db565163e0992acfde42edfd58d833_getCustomer`. 
Because of that, the method `Container::getKeyOfDemeterMockFor` will not be able to find the mock.
Some users complained about this problem in some already closed issues:
- …

Fix chained demeter calls with type hint

---

docs/reference/creating_test_doubles.rst
library/Mockery/Container.php
tests/Mockery/ContainerTest.php

Fixes https://github.com/mockery/mockery/issues/954

Add support for `!` to blacklist methods

---

docs/reference/expectations.rst
library/Mockery/Expectation.php
tests/Mockery/ExpectationTest.php

This PR is a wrapper of argument expectation.
Already custom validation for arguments can be possible to pass callback function to `withArgs`, which is good!
However, I'd like to suggest the feature to reduce our test code to prepare this wrapper method.
This method helps you to check if expected arguments are actually set when mocked methods are called.

Added an argument expectation method to check if expected arguments are parts of real arguments when mocked methods are called

---

CHANGELOG.md
docs/mockery/gotchas.rst
library/Mockery/Mock.php
tests/Mockery/ExpectationTest.php
tests/Mockery/MockClassWithMethodOverloadingTest.php
tests/Mockery/ProxyMockingTest.php

See #969
When we see a `__call` method on the parent class we can use this method when php would do the same. This way we are not limiting the developer to not use `__call` method or not mocking classes that use `__call`.
I added tests for all 3 cases. What I didn't touch is the test for the configuration. Mockery might still fail when the mocked class has a `__call` method and the configuration `allowMockingNonExistentMethods` is set to `false`. Typically for php it would return `true` when you ask `is_callable([$object, $method])` when the class has a `__call` method. Just tell me if you want this to be fixed too.

allow passing thru __call in all mock types

---

library/Mockery/Matcher/Type.php
tests/Mockery/ExpectationTest.php

Without:
```
There were 2 errors:
1) ExpectationTest::testRealConstraintMatchesArgument
Function is_real() is deprecated
/work/GIT/mockery/tests/Mockery/ExpectationTest.php:1280
2) ExpectationTest::testRealConstraintThrowsExceptionWhenConstraintUnmatched
Function is_real() is deprecated
/work/GIT/mockery/tests/Mockery/ExpectationTest.php:1296
```

don't use is_real which is deprecated in 7.4

---

library/Mockery/Container.php
tests/Mockery/ContainerTest.php

it broke our tests:
```
ErrorException: Uninitialized string offset: 0
/var/www/html/src/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php:34
/var/www/html/src/vendor/mockery/mockery/library/Mockery/Container.php:155
/var/www/html/src/vendor/mockery/mockery/library/Mockery.php:118
...
```

Bugfix: 'Add support for ! to blacklist methods' for empty methods

---

CHANGELOG.md
docs/reference/expectations.rst
library/Mockery/Expectation.php
tests/Mockery/ExpectationTest.php

Added functionality to return an argument passed to a method expectation

andReturnArgument

---

docs/cookbook/class_constants.rst

I found on obvious typo in the docs ('mock' call was used instead of a 'namedMock'), so here is the fix! Let me know if you have any comments, thank you!

docs: fix a typo in class constants section

---

README.md
docs/cookbook/mocking_hard_dependencies.rst

As it's not a practice I would like to promote, I'm moving this to the
docs, rather than have it on the README. I think for the future I would
prefer the README to be the Mockery - The Right Way type thing, the docs
contain all the juicy bits you can cut your hands on.

Move constructor expectations info to docs

---

library/Mockery/Container.php
library/Mockery/Expectation.php
library/Mockery/Mock.php
tests/Mockery/ExpectationTest.php

When using `andSet()` expectation, set the property only on instances of the current Mock rather than _all_ mocks of the same class.
Fixes issue #1005, which appears to have been inadvertently caused when fixing #451 
- Add `_mockery_instanceMock` property and `mockery_isInstance()` method.
- Set `_mockery_instanceMock` property on `mockery_init()` using config value.
- Default value is `true` if not passed (preserves existing behaviour).
- Public method `mockery_isInstance()` returns value of protected `_mockery_instanceMock`
- Only set values for current mock + instances of it.

#1005 Set properties correctly for different mocks of the same class.

---

docs/cookbook/index.rst
docs/cookbook/mocking_class_within_class.rst
docs/cookbook/mocking_hard_dependencies.rst

Explains mocking in classes with autoloading present by wrapping `new` keyword into function that can be mocked and therefore can return a prepared mock.

Add section for mocking class within class to cookbook

---

composer.json
library/Mockery/Exception/NoMatchingExpectationException.php
library/Mockery/Expectation.php
library/Mockery/ExpectationDirector.php
tests/Mockery/ContainerTest.php
tests/Mockery/ExpectationTest.php

It is often really difficult to understand and be aware of all available handlers for a given method call expectation.
Especially when the difference comes only from an entity inner property.
Here we display a list of all available handlers for the given method and for each one a diff.
Example:
```
1) Foo::testItems
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_2_Bar::get(object(Hamcrest\Core\IsEqual)). Either the method was unexpected or its arguments matched no expected argument list for this method.
Here is the list of available expectations.
Mockery_2_Bar::get with arguments:
--- Expected
+++ Actual
@@ @@
Array (
0 => Hamcrest\Core\IsEqual Object (
'_item' => Baz Object (
-            'id' => 'foo'
+            'id' => '223918237618995'
)
)
) …
```

Improve exception debugging

---

docs/reference/argument_validation.rst
library/Mockery.php
tests/Mockery/ExpectationTest.php

This adds a simple closure argument matcher which will _capture_ the argument into a local variable. This provides an easy way to store an argument passed to a mocked method for more complex validation without having to wrap all the logic inline within a `Mockery::on()` closure.
**Example:**
```php
$temp = null;
$mock->expects('foo')
->with(Mockery::capture($temp));
$mock->foo($someObject);
// $temp === $someObject
```

Add capture argument matcher

---

library/Mockery/Exception/NoMatchingExpectationException.php

This has been removed in #1000 and is breaking backwords compatibility.
People are using this method to further customize the reason the test
failed based on the actual arguments like Laravel for example: https://github.com/laravel/framework/blob/fd17b307f546f449d24d4eed1725b4941a98b895/src/Illuminate/Foundation/Testing/PendingCommand.php#L139
Thanks,
Daniel

Add back getActualArguments() to NoMatchingExpectationException

---

CHANGELOG.md
composer.json
library/Mockery/Exception/NoMatchingExpectationException.php
library/Mockery/Expectation.php
library/Mockery/ExpectationDirector.php
tests/Mockery/ContainerTest.php
tests/Mockery/ExpectationTest.php

Reverting the changes from #1000 as it broke BC and is a suspect for memory leaks.

Revert exception debugging

---

.travis.yml
Makefile

1. Test on stable PHP 7.4.
2. Allow composer to actually proceed on PHP 8.
3. Neither HHVM 3 or 4 seem to be able to even start running the tests, so I have dropped HHVM from the build.

Test on PHP 7.4 and drop HHVM

---

Makefile
docker/php70/Dockerfile
docker/php71/Dockerfile
tests/PHP70/Generator/StringManipulation/Pass/MagicMethodTypeHintsPassTest.php
tests/PHP70/MockingParameterAndReturnTypesTest.php

This PR adds php74 to makefile for local testing and moves php7.0 and php7.1 to built docker images due to phpunit version constraints.

Add php74 to makefile

---

.travis.yml

Travis already does a self-update, and the caching makes little difference to the speed. Closes #873.

Tweaked travis config

---

library/Mockery/Generator/DefinedTargetClass.php
library/Mockery/Generator/MockConfiguration.php
tests/PHP70/MockingAnonymousClassTest.php

Mockery throws a PHP Parse error when trying to mock an anonymous class.
This PR fixes this issue.

Fix mocking with anonymous classes

---

library/Mockery/Expectation.php
library/Mockery/LegacyMockInterface.php

Newer PhpStorm versions are more strict and now are warning that types don't match.
Which is basically true, since `[]` indicates that only arrays are expected.
This PR allows single mixed value as a parameter too.

Fix PHPDOC since mixed[] indicates only an array of mixed values

---

docs/reference/expectations.rst

Change misspelled "inclued" to "included".

Fix minor spelling error

---

library/Mockery/Expectation.php

The PHPDoc syntax for variadic arguments is not documented, but seems like most tools settled with this syntax:
```
/**
* @param string ...$args
*/
function variadic(string ...$args)
{
}
```

Fix DocBlocks for variadic arguments

---

CHANGELOG.md
library/Mockery/Expectation.php
tests/Mockery/ExpectationTest.php

This PR fixes the behavior in https://github.com/mockery/mockery/issues/1051
Additionally I updated an erroneous test case and added a test case for another edge case.

Fix andAnyOthers() to properly match earlier expectations

---

.gitattributes

This pull request slims down Mockery as a dependency by removing all unnecessary files from distributions. This means that if you install Mockery via Composer you will no longer have Mockery's tests and meta files in your vendor directory.

Slim down mockery when loaded as a dependency

---

composer.json
library/Mockery/Adapter/Phpunit/Legacy/TestListenerTrait.php
library/Mockery/Adapter/Phpunit/MockeryTestCase.php
tests/Mockery/Adapter/Phpunit/TestListenerTest.php
tests/Mockery/ContainerTest.php
tests/Mockery/ExpectationTest.php

This adds support for PHPUnit version 9.
PHPUnit version 9.1.2 had a breaking change in then `@internal` marked `Blacklist` class, which was addressed in [9.1.3](https://github.com/sebastianbergmann/phpunit/blob/74a7e9b91281f5051da617fdb2201c0d619b9efe/ChangeLog-9.1.md#913---2020-04-23).
Fixes #1048

Add support for PHPUnit version 9

---

library/Mockery/Mock.php

Fixed "TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given"

---

library/Mockery/Generator/Method.php

I was trying to mock some classes from php-couchbase and got the following error:
ParseError : syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)
This error is coming from the generated mock class and is caused by return types of methods which are prefixed with a `\`.
Adding a `\` in the return type in PHP itself does not cause this issue, but this extension defines their classes and method return types in C. The prefixed `\` is not stripped off because of that.
For example, a method with a return type is defined like this:
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(ai_Cluster_bucket, 0, 1, \\Couchbase\\Bucket, 0)
But it should probably be defined like this:
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(ai_Cluster_bucket, 0, 1, Couchbase\\Bucket, 0)
This is probably more …

Don't prefix return type with \ if it already is prefixed with \

---

CHANGELOG.md
docs/mockery/configuration.rst
library/Mockery/Configuration.php
library/Mockery/Container.php
library/Mockery/QuickDefinitionsConfiguration.php
tests/Mockery/ExpectationTest.php

…t expectations set through quick definitions

Add option to allow\disallow mocking methods unnecessarily for default expectations defined through quick definitions

---

library/Mockery/Mock.php
phpunit.xml.dist
tests/PHP71/Php71LanguageFeaturesTest.php

[1.3] Support iterable and removed uneeded check

---

CHANGELOG.md
composer.json

Closes https://github.com/mockery/mockery/pull/1080.

[1.4] Release 1.4.1

---

library/Mockery/Generator/StringManipulation/Pass/ConstantsPass.php
tests/Mockery/Fixtures/ClassWithConstants.php
tests/Mockery/MockingClassConstantsTest.php

Fix: array to string conversion in ConstantsPass [1.3]

---

.styleci.yml
library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
library/Mockery/Matcher/MultiArgumentClosure.php
tests/Mockery/Fixtures/SemiReservedWordsAsMethods.php
tests/PHP70/MockingParameterAndReturnTypesTest.php

1. Disable PHP 5.6 non-compatible PSR-12 fixer.
2. Allow short closures (it was a bug that StyleCI allowed them in the old PSR-12 preset).
3. Apply remaining fixes from StyleCI.
---
Travis is currently failing due to further PHP 8.0 changes, which I will address later this week when I work on https://github.com/mockery/mockery/issues/1083.

[1.3] Fixed StyleCI config

---

.styleci.yml
.travis.yml
composer.json
library/Mockery/Container.php
library/Mockery/Generator/Parameter.php
library/Mockery/Generator/StringManipulation/Pass/MagicMethodTypeHintsPass.php
library/Mockery/Matcher/MultiArgumentClosure.php
library/Mockery/Reflector.php
phpunit.xml.dist
tests/Mockery/Fixtures/SemiReservedWordsAsMethods.php
tests/PHP70/MockingParameterAndReturnTypesTest.php
tests/PHP80/Php80LanguageFeaturesTest.php

This PR addresses some issues from the previous PR, some of which were caused by additional changes made to PHP 8.0, after the other PR was done. This doesn't address automatic creation of return values for methods typed as `static`. I am not sure if we even want to support this...
---
Depends on https://github.com/mockery/mockery/pull/1087. Related to https://github.com/mockery/mockery/issues/1083.

[1.3] Improved PHP 8.0 support

---

library/Mockery.php
library/Mockery/ExpectationInterface.php
library/Mockery/Matcher/MatcherAbstract.php

Just a small update to a few type hints to prevent IDEs from flagging. Below is a screenshot using PhpStorm.
Thank you for this awesome lib! 🚀

Update type hints

---

.travis.yml

This solve issues with PHPUnit and Xdebug 3.0 when running tests for PHP 7.3 and 7.4.
mockery has basically no dependencies so the part of the matrix testing with '--prefer-lowest' brings little/no value.
See the discussion in https://github.com/mockery/mockery/pull/1106#issuecomment-739831499

Stop testing with '--prefer-lowest'

---

library/Mockery/Reflector.php
tests/PHP80/Php80LanguageFeaturesTest.php

This change prevents the generation of type hints with 2 "null".
For example, "string|array|null" should generate the code "string|array|null" instead of "string|array|null|null" to avoid a PHP fatal error "Duplicate type null is redundant".
Closes #1105.

Fix crash on a union type including null

---

.gitignore
Makefile

phpDocumentor cache has been added to the .gitignore so it does not end up committed into the repo/a PR by mistake.

Build API docs with phpDocumentor 3.0.0 final instead of RC

---

library/Mockery.php

See #1113
> Calling `Mockery::fetchMock()` first doesn't make much sense and likely indicates a logic error, but Mockery should nevertheless throw `Call to a member function fetchMock() on null` errors.
> 
> Maybe we should throw a `LogicException` instead when no container was initialized yet (just like `Mockery::self()`)? If no container was initialized yet, `Mockery::fetchMock()` will always return `null`, just like if the mock in question simply doesn't exist (yet). Other opinions?

Fix Mockery::fetchMock() without initialized container (1.3 branch)

---

library/Mockery/LegacyMockInterface.php

Current type hint suggests that $args can only be null, and static analysis tools complain when you call the method with something else.
Add types that you can pass to withArgs.
Thanks

fix shouldHaveReceived $args param typehint

---

library/Mockery.php
library/Mockery/Configuration.php
tests/Mockery/WithCustomFormatterExpectationTest.php

Possibility to set custom objet formatters for specific classes or interfaces. If formatter is set it's used instead of default formatter outputing public properties.
```
\Mockery::getConfiguration()->setObjectFormatter(
'ClassWithCustomFormatter',
function($object) {
return array(
"properties" => array(
"stringProperty" => $object->stringProperty
),
"getters" => array(
"gettedProperty" => $object->getArrayProperty()
)
);
}
);
```

Custom object formatters

---

docs/reference/final_methods_classes.rst

Use of interfaces in final classes removes the need for proxy mocks.

Advocate for the use of interfaces, rather than against the use of final

---

CHANGELOG.md
library/Mockery/Expectation.php
tests/Mockery/ExpectationTest.php

Add method that allows defining a set of arguments the mock should yield

---

library/Mockery/Mock.php
library/Mockery/Reflector.php
tests/Mockery/ContainerTest.php
tests/PHP80/Php80LanguageFeaturesTest.php

- Avoid passing null to non-nullable parameters of internal functions
- Skip `Serializable` test on PHP <8.1
- Add support for tentative return types

Fixes for PHP 8.1

---

library/Mockery/Expectation.php

Previously `andReturnArg` threw an exception with the message `Invalid argument index supplied. Index must be a positive integer.`. However this is confusing because the method accepts the number `0`. 
This PR changes the wording to `non-negative integer` to be more accurate.

Update error message to be more accurate

---

docs/mockery/reserved_method_names.rst

Updated the reserved methods in the docs. I am curious what `shouldBeStrict()` was?

updated reserved methods in docs

---

library/Mockery/Mock.php
library/Mockery/Reflector.php
tests/PHP81/Php81LanguageFeaturesTest.php

Same as https://github.com/mockery/mockery/pull/1143 for the 1.4 branch. Easier than dealing with those merge PRs.
---
Blocks https://github.com/laravel/framework/pull/38404. cc @davedevelopment, @driesvints.

[1.4] Fix auto-generated return values with union types

---

library/Mockery/Mock.php
library/Mockery/Reflector.php
tests/PHP81/Php81LanguageFeaturesTest.php

The logic is now:
* if nullable or no return type, return null
* otherwise, return a primitive if possible
* otherwise, mock the first class in the type and return that
So, `int|false` will auto-return `0` and `Foo|false` will auto-return `false`. The old logic was very similar, but broken because it looked at the string `int|false`, decided it was not primitive, and then tried to mock it.
---
Before fix:
```
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.1.0RC1
Configuration: /data/phpunit.xml.dist
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
....................R...................W......................  63 / 615 ( 10%) …
```

[1.3] Fix auto-generated return values with union types

---

library/Mockery/Mock.php
tests/Mockery/Fixtures/MethodWithStaticReturnType.php
tests/Mockery/MockingMethodsWithStaticReturnTypeTest.php

This patch resolves #1155, via the following changes:
- Add tests and fixtures
- Mock methods with `static` return type.
``` php
class Foo
{
public function getFoo(): static
{
return $this;
}
}
```

Mock methods with `static` return types

---

library/Mockery.php
tests/Mockery/MockingMethodsWithMixedReturnTypeTest.php

This patch resolves #1149, via the following changes:
- Add tests and fixtures
- Mock methods with `mixed` return type.
``` php
class MockingMethodsWithMixedReturnTypeTest extends MockeryTestCase
{
public function testMockingMixedReturnType()
{
$mock = \Mockery::mock(MyInterface::class);
$mock->shouldReceive("foo->bar")->andReturn("bar");
$this->assertSame('bar', $mock->foo()->bar());
}
}
interface MyInterface {
public function getFoo(): mixed;
}
```

Mock methods with `mixed` return type

---

.github/workflows/tests.yml
CHANGELOG.md
library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
phpunit.xml.dist
tests/PHP81/Php81LanguageFeaturesTest.php

This patch resolves #1154, via the following changes:
- Add tests and fixtures 
- Mock classes with `new` in initializers

Mock classes with `new` in initializers on PHP 8.1

---

library/Mockery/Generator/StringManipulation/Pass/RemoveBuiltinMethodsThatAreFinalPass.php
tests/Mockery/MockClassWithFinalToStringTest.php

Fixes #1153 by adding __toString to array of methods to be removed in generator pass

Add __toString to array of methods to be removed in pass

---

tests/Mockery/MockClassWithFinalToStringTest.php

Follow up on PR #1162, which introduced a new test which again set a dynamic property.

PHP 8.2 | Tests: fix newly introduced dynamic property

---

.github/workflows/tests.yml
phpunit.xml.dist

PHP 8.2 is likely to cause significant amounts of deprecation notices again in most projects.
As Mockery is a testing tool and projects will use their tests as a starting point to start fixing their code, it would be wonderful for Mockery to be PHP 8.2 ready early (before PHP 8.2-beta1).
PR #1168, #1170 and #1174 fix the bulk of the issues in Mockery itself as found via Mockery's own tests. As of now and with the WIP current state of PHP 8.2, there are only 11 failing tests left.
To keep on top of what additional work is and will be still needed to make Mockery compatible with PHP 8.2, I propose to start running the tests against PHP 8.2 in GitHub Actions.
... for early warning about problems which need addressing.
For now, a failing test run against PHP 8.2 won't stop the build. …

GH Actions: run tests against PHP 8.2

---

.phpstorm.meta.php

After the fix of https://youtrack.jetbrains.com/issue/WI-60544 type() meta directive won't treat string literals contents as types anymore, prefered way is to use (map([""=>"$0"])). This PR updates meta file according to preferred way.

update meta to properly infer type of string parameters

---

library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
tests/PHP81/Php81LanguageFeaturesTest.php

This patch resolves #1167, via the following changes:
- MethodDefinitionPass will not generate a `return` statement for a `never` return typehint.
A function/method that is declared with the `never` return type indicates that it will never `return` a value, and **always** throws an exception or terminates with a `die/exit `call.

[8.1] Support `never` return type

---

CHANGELOG.md

In response to issue #1190, I have updated the documentation to record the changes from #1180 
I haven't labelled the change as a BC break to avoid contention; the scope of this MR is purely to make people aware that the change happened. To that end, I hope we can release this under 1.5.2 quickly, even if this is the only change.

Update the changelog to include changes from #1180

---

library/Mockery/Reflector.php
tests/PHP81/Php81LanguageFeaturesTest.php

Fixes code generation for intersection types

---

tests/Mockery/AllowsExpectsSyntaxTest.php
tests/Mockery/ContainerTest.php
tests/Mockery/ExpectationTest.php
tests/Mockery/MockTest.php
tests/Mockery/MockeryCanMockMultipleInterfacesWhichOverlapTest.php
tests/Mockery/MockingNullableMethodsTest.php
tests/Mockery/MockingVoidMethodsTest.php
tests/PHP80/Php80LanguageFeaturesTest.php
tests/PHP81/Php81LanguageFeaturesTest.php

This patch includes the following changes:
- Updates failing and or risky tests

Refactoring risky tests

---

library/Mockery/Reflector.php
tests/PHP82/Php82LanguageFeaturesTest.php

Because the `null` type in PHP 8.2 is nullable, the `formatNullableType` method appends `|null` to the`null` type. This results in `null|null` as a generated return type. When parsing, this results in the following error:
```
PHP Fatal error:  Duplicate type null is redundant 
```
This PR fixes this by simply formatting returning `null` when the passed type is `null`.
Fixes #1204.

Deal with null type in PHP8.2

---

phpunit.xml.dist

This pull request updates the `phpunit.xml.dist` configuration file to exclude tests based on the PHP version that is being used.
This will allow us to run tests for different PHP versions in isolation, which will make it easier to identify and fix issues that are specific to certain PHP versions.

Split PHPUnit TestSuites for PHP 8.2

---

.github/workflows/tests.yml

This pull request updates `actions/checkout` from v2 to v3.

Bump `actions/checkout` to v3

---

.github/workflows/psalm.yml
.github/workflows/tests.yml

This patch limits the CI actions to only run on `push` events, on branches matching the regex to prevent duplicate runs in pull requests.

Prevent CI run duplication

---

.github/workflows/codecov.yml
README.md
codecov.yml
phpunit.xml.dist

This PR enables Codecov GitHub Action and Comments for code coverage.
- Create codecov.yml GitHub workflow
- Create codecov.yml Config file
Codecov provides a detailed report on the test coverage of the codebase and helps identify areas that need additional tests.
Follow the steps to finish setting up code coverage. https://app.codecov.io/gh/mockery/mockery/new
Once it's set up, visit this link to grab the markdown code for a Codecov badge https://app.codecov.io/gh/mockery/mockery/settings/badge
You can leave the markdown in a comment here, i'll update the readme with that information.
GitHub will also email you regarding my request to allow Codecov access to public organization data (read-only access to the repo).

Setup `Codecov` for code coverage

---

.phpstorm.meta.php

This pull request updates the PHPStorm `>=2021.3` metadata file to support Intersection Types.
References:
[Blog post on PHPStorm 2021.3 release](https://blog.jetbrains.com/phpstorm/2021/12/phpstorm-2021-3-release/#pure_intersection_types)
[PHPStorm documentation on advanced metadata mapping](https://www.jetbrains.com/help/phpstorm/ide-advanced-metadata.html#map)
An example of the changes made to the meta file: 
```diff
- override(\mock(0), map(["" => "@"]));
+ override(\mock(0), map(["" => "@&\ArrayAccess"]));
```
These changes will enable developers using PHPStorm to take full advantage of Intersection Types when mocking objects.
This will be followed by an additional PR adding the doc comments to indicate intersection types for static analysis tools.
```
/** 
* @template T of object
* …
```

Update PHPStorm metadata to support Intersection Types

---

library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
tests/PHP81/Php81LanguageFeaturesTest.php

Fix function parameter default enum value

---

composer.json
library/Mockery/Generator/DefinedTargetClass.php
library/Mockery/Generator/StringManipulation/Pass/ClassAttributesPass.php
library/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
library/Mockery/Generator/UndefinedTargetClass.php
library/Mockery/Mock.php
psalm-baseline.xml
psalm.xml.dist
tests/Mockery/Generator/StringManipulation/Pass/ClassAttributesPassTest.php
tests/PHP81/Php81LanguageFeaturesTest.php

This patch adds the `\AllowDynamicProperties` attribute on the mock object by default.
- Allows us to use `set` and `andSet` to dynamically set properties on the object after the mock instance is created.
- `DefinedTargetClass` Appends all additional attributes on PHP >= 8.0, via `\ReflectionAttribute`

Improve `ClassAttributesPass` for Dynamic Properties

---

library/Mockery/CountValidator/Exception.php
library/Mockery/Exception.php
library/Mockery/Exception/BadMethodCallException.php
library/Mockery/Exception/InvalidArgumentException.php
library/Mockery/Exception/MockeryExceptionInterface.php
library/Mockery/Exception/RuntimeException.php

If accepted, this patch adds.
- `MockeryExceptionInterface`
- Implements `MockeryExceptionInterface` on Mockery's Exception classes.
> As of https://github.com/sebastianbergmann/phpunit/commit/74ce5b661a74b488e4a515256b9f35c5a8562683, all exceptions thrown in third-party subscribers are ignored.
This will allow us to register all of Mocker's Exceptions as PHPUnit failures via `TestCase::registerFailureType()` implemented in https://github.com/sebastianbergmann/phpunit/commit/28766f5aac456f8093a1e946aad79c9cf96bb0ca for `PHPUnit 10.1`.
`TestCase::registerFailureType(MockeryExceptionInterface::class)` in `MockeryTestCase`

Add `MockeryExceptionInterface`

---

.github/workflows/tests.yml

This patch cleans up the `.github/workflows/tests.yml` and adds `8.3`

Add PHPUnit workflow for PHP 8.3 

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml

This patch adds Issue templates to the repo.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

Add `BUG_REPORT.yml` Issue template

---

composer.json

The `composer.json`'s branch alias for 1.5.x points to 1.4.x-dev version.
This is making requirements for the _next_ unreleased 1.5.x impossible, unless explictly requiring the branch.

Update branch alias for 1.6.x

---

library/Mockery/Mock.php
tests/PHP82/Php82LanguageFeaturesTest.php

This pull request introduces support for [Literal Types](https://www.php.net/manual/en/language.types.literal.php) in PHP 8.2, specifically focusing on the `false` literal type.

Support PHP 8.0 `false` Literal Type

---

library/Mockery/Matcher/IsSame.php
psalm-baseline.xml
tests/Mockery/Matcher/IsSameTest.php
tests/Mockery/Matcher/MatcherDataProviderTrait.php

This pr adds an `IsSame` [Argument Matcher](http://docs.mockery.io/en/latest/reference/argument_validation.html#additional-argument-matchers)

Add `IsSame` Argument Matcher

---

library/Mockery/Matcher/IsEqual.php
psalm-baseline.xml
psalm.xml.dist
tests/Mockery/Matcher/IsEqualTest.php
tests/Mockery/Matcher/MatcherDataProviderTrait.php

This pr adds an `IsEqual` [Argument Matcher](http://docs.mockery.io/en/latest/reference/argument_validation.html#additional-argument-matchers)
Resolves #1268

Add `IsEqual` Argument Matcher

---

composer.json
composer.lock

This PR use composer `config.platform.php` to define the minimum required PHP version that Mockery supports.
It will also ensure that all dependencies are compatible with that PHP version.

Enforce the minimum required PHP version

---

.github/workflows/tests.yml

This PR updates the `tests.yml` workflow to use `ramsey/composer-install`, A GitHub Action to streamline the installation of PHP dependencies with Composer.

Update phpunit workflow

---

psalm-baseline.xml
src/Mockery/LegacyMockInterface.php
src/Mockery/Mock.php

This PR should fix old problem when phpstan stop working correctly with Mockery when you do something like `$mock = Mockery::mock(SomeClass::class)->shouldIgnoreMissing();`

Correct return types of Mock for phpstan

---

Makefile

This patch updates the makefile to update the docker images and commands we use for development.
- Run PHPUnit on PHP 7.4 -8.3 via `make test-all`

Update `Makefile` for contributors

---

composer.json
composer.lock
psalm-baseline.xml
src/Mockery/Generator/StringManipulation/Pass/MethodDefinitionPass.php
tests/Fixture/PHP81/A.php
tests/Fixture/PHP81/B.php
tests/Fixture/PHP81/C.php
tests/Fixture/PHP81/HandlerClass.php
tests/Fixture/PHP81/MockClass.php
tests/Fixture/PHP81/SomeAttribute.php
tests/Unit/PHP81/Php81LanguageFeaturesTest.php

Fix mocking classes with `new` initializers in method and attribute params on PHP 8.1

---

composer.json

This pull request proposes an update to the composer.json file in order to update composer information and remove the `extra.branch-alias` section.
- Removed the `extra.branch-alias` section as branch aliases are no longer maintained. We now have dedicated release branches for each major and minor version. (eg. `1.6.x-dev` and `2.0.x-dev`)
- Replaced dead links with GitHub profile links.
- Added and updated authors with their respective roles.
- Added support links and information to help users find resources and get assistance.

Remove `extra.branch-alias` and update composer information

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/workflows/codecov.yml
.github/workflows/psalm.yml
.github/workflows/tests.yml
Makefile
composer.json
composer.lock
library/Mockery/Generator/DefinedTargetClass.php
library/Mockery/Reflector.php
phpunit.xml.dist
psalm-baseline.xml
psalm.xml.dist
tests/Mockery/Matcher/SubsetTest.php

This pull request addresses compatibility issues with PHP 7.3, 
We have reviewed the reported problems and made necessary adjustments to align with PHP 7.3's syntax and requirements.
Our aim is to maintain broad compatibility and offer a seamless experience for users using older PHP versions.
Please review the changes, and if there are any additional concerns, kindly let us know.
Thank you

Fix compatibility issues with PHP 7.3

---

docs/reference/spies.rst

This change fixes a misspelled word in the documentation page for spies.

Fix misspelling in docs

---

library/Mockery/Loader/RequireLoader.php

This pull request proposes to make the following changes:
- cleans up mocks created by `RequireLoader` on `__destruct`.

Clean up mocks on destruct

---

composer.json
fixtures/autoload.php
psalm-baseline.xml

This pull request adds functionality to autoload test fixtures based on the runtime version of PHP. 
This will help ensure that the correct fixtures are loaded when running tests on different PHP versions.
Please review the changes, and if there are any additional concerns, kindly let us know.
Thank you

Autoload Test Fixtures Based on PHP Runtime Version

---

CHANGELOG.md
psalm-baseline.xml

- [#1321: Autoload Test Fixtures Based on PHP Runtime Version](https://github.com/mockery/mockery/pull/1321)
- [#1320: Clean up mocks on destruct](https://github.com/mockery/mockery/pull/1320)
- [#1318: Fix misspelling in docs](https://github.com/mockery/mockery/pull/1318) by @asemarian
- [#1316: Fix compatibility issues with PHP 7.3](https://github.com/mockery/mockery/pull/1316)
- [#1315: Fix PHP 7.3 issues](https://github.com/mockery/mockery/issues/1315)
- [#1314: Add Security Policy](https://github.com/mockery/mockery/pull/1314)
- [#1313: Type declaration for `iterable|object`.](https://github.com/mockery/mockery/pull/1313)
- [#1312: Mock disjunctive normal form types](https://github.com/mockery/mockery/pull/1312)
- [#1299: Test PHP `8.3` language …

Changelog v1.6.5

---

library/Mockery/Loader/RequireLoader.php

- register a shutdown to perform the clean-up on error
- remove all the mocks we generated except the file that caused the last error, on exit.

Keep the file that caused an error for inspection

---

library/Mockery/Reflector.php

Fix #1323 - https://3v4l.org/JFpUQ
> The + operator returns the right-hand array appended to the left-hand array; for keys that exist in both arrays, the elements from the left-hand array will be used, and the matching elements from the right-hand array will be ignored.
https://www.php.net/manual/en/language.operators.array.php
> Merges the elements of one or more arrays together so that the values of one are appended to the end of the previous one. It returns the resulting array.
> If the input arrays have the same string keys, then the later value for that key will overwrite the previous one. If, however, the arrays contain numeric keys, the later value will not overwrite the original value, but will be appended.
> Values in the input arrays with numeric keys will be renumbered with …

Replace `+` Array Union Operator with `array_merge`

---

.github/workflows/tests.yml

This patch enables testing `PHP 8.4` via the following changes:
- Add `8.4`  to `.github/workflows/tests.yml`

Setup PHP 8.4 CI Tests

---

library/Mockery.php
tests/Mockery/Matcher/IsEqualTest.php
tests/Mockery/Matcher/IsSameTest.php

Add factory methods for `IsEqual` and `IsSame` matchers

---

docs/reference/expectations.rst

Semicolumn is misplaced and should be removed

docs: Remove misplaced semicolumn from code snippet

---

.readthedocs.yml
docs/conf.py
docs/reference/index.rst
docs/requirements.txt

This patch resolves failing documentation build process for docs.mockery.io, via the following changes:
- [Add .readthedocs.yml](https://github.com/mockery/mockery/commit/f1f12c42abcd559e0af2d1413c097a5094a477fd)
- [Add requirements.txt](https://github.com/mockery/mockery/commit/9926379aee4d564a666c527b81a9e80122387725)
- [Update conf.py](https://github.com/mockery/mockery/commit/4260ba611b58b7ae8a01b394b06f02f75c6d00d3)

Add `.readthedocs.yml` configuration

---

CHANGELOG.md

- [1351: Update psalm-baseline.xml](https://github.com/mockery/mockery/pull/1351)
- [1350: Changelog v1.6.7](https://github.com/mockery/mockery/pull/1350)
- [1349: Cleanup](https://github.com/mockery/mockery/pull/1349)
- [1348: Update makefile](https://github.com/mockery/mockery/pull/1348)
- [1347: Bump phars dependencies](https://github.com/mockery/mockery/pull/1347)
- [1346: Fix test namespaces](https://github.com/mockery/mockery/pull/1346)
- [1344: Disabled travis-ci and sensiolabs webhooks](https://github.com/mockery/mockery/issues/1344)
- [1343: Update documentation default theme and build version](https://github.com/mockery/mockery/pull/1343)
- [1342: Add `.readthedocs.yml` configuration](https://github.com/mockery/mockery/pull/1342)
- [1340: docs: Remove misplaced semicolumn from …

Changelog v1.6.7
